"""
Project Euler Problem 12: Highly Divisible Triangular Number
https://projecteuler.net/problem=12

The sequence of triangular numbers is generated by adding the natural
numbers: the nth triangular number is 1 + 2 + ... + n.

The first ten are: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Listing the factors of the first seven:
    1: 1
    3: 1, 3
    6: 1, 2, 3, 6
   10: 1, 2, 5, 10
   15: 1, 3, 5, 15
   21: 1, 3, 7, 21
   28: 1, 2, 4, 7, 14, 28
The first triangular number with over five divisors is 28.

What is the value of the first triangular number to have over five
hundred divisors?
"""


def num_divisors(x):
    """Count divisors of x via the product of (exponent + 1) over its primes.

    Example: 28 = 2^2 * 7  ->  (2+1)(1+1) = 6 divisors.
    """
    count = 1
    d = 2
    while d * d <= x:
        if x % d == 0:
            exponent = 0
            while x % d == 0:
                x //= d
                exponent += 1
            count *= exponent + 1
        d += 1
    if x > 1:
        # a leftover prime factor appears once: (1 + 1)
        count *= 2
    return count


def solve(target=500):
    # Walk the triangular numbers: x grows by i each step (x = 1+2+...+i).
    i = 1
    x = 1
    while num_divisors(x) <= target:
        i += 1
        x += i
    return x


if __name__ == "__main__":
    import time

    start = time.perf_counter()
    answer = solve()
    elapsed_ms = (time.perf_counter() - start) * 1000

    print(f"Answer: {answer}  ({num_divisors(answer)} divisors)")
    print(f"Time:   {elapsed_ms:.1f} ms")
